feat(OX-3565) add oxeye scan action
ox-eye/github-actions pull request #22
Opened 2023-08-22 06:00 UTC by oxeye-schmil

2023-08-22 13:52 UTC, DovnarAlexander requested changes

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +FROM golang:1.19-alpine3.18 AS oxctl_builder
Let's use [ecr images ](https://gallery.ecr.aws/docker/library/golang) to save dockerhub quotas

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +FROM alpine:3.18.0 AS downloader
Let's use [ecr images ](https://gallery.ecr.aws/docker/library/alpine) to save dockerhub quotas

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +    apk add git && \
Let's add --no-cache to keep cache smaller

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +    git clone https://github.com/returntocorp/semgrep-rules $SEMGREP_CONFIG_DIR/semgrep-rules && \
We can do cloning here directly on specific SHA\REF (see 13th line)

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +RUN apk update && apk add --update --no-cache \
Let's add `rm -rf /var/cache/apk/*` to remove updated packages' indices to keep final image smaller

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +FROM alpine:3.18
Let's use [ecr images ](https://gallery.ecr.aws/docker/library/alpine)to save dockerhub quotas

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +RUN pip install semgrep==1.22.0
Let's use `--no-cache-dir` to keep final image smaller

2023-08-22 13:52 UTC, DovnarAlexander requested changes

2023-08-22 13:52 UTC, DovnarAlexander commented on images/Dockerfile.oxeye-scan
> +FROM alpine:3.18
Let's use [ecr images ](https://gallery.ecr.aws/docker/library/alpine)to save dockerhub quotas

2023-08-22 13:56 UTC, oxeye-schmil commented on images/Dockerfile.oxeye-scan
> +FROM alpine:3.18.0 AS downloader
done

2023-08-22 13:59 UTC, oxeye-schmil commented on images/Dockerfile.oxeye-scan
> +FROM golang:1.19-alpine3.18 AS oxctl_builder
done

2023-08-22 14:02 UTC, oxeye-schmil commented on images/Dockerfile.oxeye-scan
> +    apk add git && \
done

2023-08-22 14:04 UTC, oxeye-schmil commented on images/Dockerfile.oxeye-scan
> +RUN apk update && apk add --update --no-cache \
done

2023-08-22 14:06 UTC, oxeye-schmil commented on images/Dockerfile.oxeye-scan
> +    git clone https://github.com/returntocorp/semgrep-rules $SEMGREP_CONFIG_DIR/semgrep-rules && \
We want to get the most updated rules every time

2023-08-23 11:36 UTC, DovnarAlexander approved these changes

2023-08-23 11:37 UTC, merged